routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', function() {
    return redirect()->route('home');
});


//mbtodo auth?
Route::get('/new-user-reset/{token}/{id}', 'UserController@newUserReset')->name('new-user-reset');
Route::post('/new-user-reset', 'UserController@savePassword')->name('new-user-save-password');




Route::get('/', 'DashboardController@index')->name('home');

Route::get('/message-page', 'DashboardController@messagePage')->name('message-page');


//Route::get('/login/with-aad/{context?}', 'Auth\External\AzureActiveDirectoryController@login')->name('login.aad');
Route::get('/login/with-aad', 'Auth\External\AzureActiveDirectoryController@loginStart')->name('login.aad.start');
Route::get('/login/with-aad/{application?}', 'Auth\External\AzureActiveDirectoryController@loginResponse')->name('login.aad.response');
Route::get('/logout/with-aad/{application?}', 'Auth\External\AzureActiveDirectoryController@logout');

//user groups

Route::group(['middleware'=>'auth'], function() {

    Route::get('user-groups/select', 'UserGroupController@selectList')->name('user-groups.select-list');
    Route::post('user-groups/select', 'UserGroupController@select')->name('user-groups.select');



    Route::get('user-groups/admin', 'UserGroupController@admin')->name('user-groups.admin');
    Route::get('user-groups/link', 'UserGroupController@initiateLink')->name('user-groups.link');
    Route::get('user-groups/select/none', 'UserGroupController@selectNone')->name('user-groups.select-none');


    Route::get('user-groups/deselect/{user_group}', 'UserGroupController@deselect')->name('user-groups.deselect');
    Route::get('user-groups/request-access/{user_group}', 'UserGroupController@requestAccess')->name('user-groups.requestaccess');
    Route::get('user-groups/autocomplete', 'UserGroupController@autocomplete')->name('user-groups.autocomplete');
    Route::resource('user-groups', 'UserGroupController');


    Route::resource('users','UserController');


});



//Created a new group, without the azure prefix
Route::group(['middleware'=>'auth', 'namespace'=>'CloudService'], function() {

    //Agreements
    Route::get('agreements/make', 'AgreementController@make')->name('agreements.make');
    Route::resource('agreements', 'AgreementController');
    Route::get('agreements/{agreement}/delete', 'AgreementController@delete')->name('agreements.delete');
    Route::get('agreements/{agreement}/discover', 'AgreementController@discover')->name('agreements.discover');
    Route::get('agreements/{agreement}/add-subscription', 'AgreementController@addSubscription')->name('agreements.add-subscription');

    //Margins
    Route::get('agreements/{agreement}/margins', 'AgreementController@showMargins')->name('agreements.margins.show');
    Route::get('agreements/{agreement}/margins/edit', 'AgreementController@editMargins')->name('agreements.margins.edit');
    Route::post('agreements/{agreement}/margins', 'AgreementController@storeMargins')->name('agreements.margins.store');


});


Route::group(['middleware'=>'auth', 'namespace'=>'CloudService', 'prefix'=>'/services/azure'], function() {
    Route::get('', 'AzureController@index')->name('azure.index');
    //Route::get('discover', 'AzureController@discover')->name('azure.discover');
    Route::get('subscriptions/{subscription}/usage', 'AzureSubscriptionController@usage')->name('azure.subscriptions.usage');

    Route::resource('subscriptions', 'AzureSubscriptionController', ['as'=>'azure']);
    Route::get('subscriptions/{subscription}/delete', 'AzureSubscriptionController@delete')->name('azure.subscriptions.delete');
    Route::get('subscriptions/{subscription}/connect', 'AzureSubscriptionController@connect')->name('azure.subscriptions.connect');
    Route::post('subscriptions/{subscription}/attach', 'AzureSubscriptionController@attach')->name('azure.subscriptions.attach');
    Route::get('subscriptions/{subscription}/check', 'AzureSubscriptionController@check')->name('azure.subscriptions.check');
});

Route::group(['middleware'=>'auth', 'namespace'=>'CloudService', 'prefix'=>'/services/aad'], function() {
    Route::get('tenants/{aadTenant}/connect/{applicationName?}', 'MicrosoftAadTenantController@connect')->name('aad.tenants.connect');
    Route::post('tenants/{aadTenant}/attach/{applicationName?}', 'MicrosoftAadTenantController@attach')->name('aad.tenants.attach');
});



// TESTS! ---------------------------------------------------------------------------------------------------------------
Route::get('/azure-test', 'CloudService\AzureController@test')->name('azure.test');
Route::get('/tests', 'TestController@index');
Route::get('/tests/ea', 'TestController@eaApi');
Route::get('/tests/partner', 'TestController@partnerApi');
Route::get('/tests/reports', 'TestController@reports');
Route::get('/tests/add-azure-agreement/{which}', 'TestController@addAzureAgreement');

Route::group(['middleware'=>'auth', 'prefix'=>'/data'], function() {
    Route::get('/azure/agreements/count', 'DataController@azureAgreementCount');
    Route::get('/azure/subscriptions/count', 'DataController@azureSubscriptionCount');
    //Route::get('/azure/spend/{month?}', 'DataController@azureSpend');
    //Route::get('/azure/spend2', 'DataController@azureSpend2');
    Route::get('/azure/spend', 'DataController@azureSpend');
});

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

//Form Request
use App\Events\UserCreated;
use App\Http\Requests\StoreUser;

//Models
use App\Models\User;
use App\Models\UserGroup;

//Events
use App\Listeners\EmailNewUser;

use Illuminate\Support\Facades\Request;

use Illuminate\Support\Facades\DB;


class UserController extends Controller
{
    public function __construct()
    {
        //User group must be selected for all these functions
        $this->middleware('userGroupSelected')->except('newUserReset','savePassword');
    }


    /**
     * This where the user gets sent, when they have clicked
     * the email link. Check the token, then send them to the
     * reset view.
     *
     * @param Request $request
     * @param $token
     * @param $user_id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function newUserReset(Request $request, $token,$user_id)
    {
        $user = User::findOrFail($user_id);

        if (! $user->checkToken($token)) {
            showMessage('danger','The link you clicked is invalid.');

            return redirect()->to('/login');
        }else {

            return view('users.welcome')->with([
                'token' => $token,
                'email' => $user->email,
                'user' => $user
            ]);
        }
    }

    /**
     * Display list of users.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function index()
    {
        $this->authorize('index', User::class);

        //what user should we see
        //just the selected group?
        $users = User::where('user_group_id', '=', UserGroup::getSelectedGroupID())->get();

        $canEdit = true;

        return view('users.index', compact('users', 'canEdit'));
    }

    /**
     * Show the form to create new.
     *
     * @param User $user
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create(User $user)
    {
        $this->authorize('create', User::class);

        $roles = collect(User::ROLES);

        $userGroups = UserGroup::getTreeForSelectedUser();

        $title = "User Group";

        $user->user_group_id = UserGroup::getSelectedGroupID();

        return view('users.create', compact('user', 'roles','userGroups','title'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreUser $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request)
    {
        //auth in form request

        $user = new User();
        $user->name = $request->name;
        $user->email = $request->email;
        $user->role = $request->role;
        $user->status = User::STATUS_INVITED;
        $user->user_group_id = UserGroup::getSelectedGroupID();

        if (!$user->isAadUser()){
            $user->password = str_random(8);
        }

        $user->save();

        event(new UserCreated($user)); //fire event that send email

        return redirect()->route('users.show', [$user]);
    }

    /**
     * Display the specified resource.
     *
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(User $user)
    {
        $this->authorize('show', $user);

        return view('users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param User $user
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(User $user)
    {
        $this->authorize('edit', $user);

        $roles = collect(User::ROLES);

        $userGroups = UserGroup::getTreeForSelectedUser();

        $title = "User Group";

        return view('users.edit', compact('user', 'roles','userGroups','title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param StoreUser $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function update(StoreUser $request, User $user)
    {

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->role = $request->input('role');
        $user->user_group_id = $request->input('user_group_id');
        $user->save();

        $request->session()->flash('message', 'User updated');

        return redirect()->route('users.show', [$user]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param User $user
     * @return void
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(User $user)
    {
        $this->authorize('destroy', $user);

        User::destroy($user->id);

        showMessage('success', 'User deleted');
    }














}

resources/views/users/create.blade.php
@extends('layouts/main')

@section('title', 'Add a User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a User</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('users.store') }}">
                            {{ csrf_field() }}

                            @include('users/partials/fields')

                            <div id="app"> {{--The Vue application--}}
                                <bss-tree options-string="{{$userGroups}}"
                                          title="{{$title}}"
                                          initial-id = "{{$user->user_group_id}}">
                                </bss-tree>
                            </div> {{--app--}}

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Add User
                                    </button>

                                    <a class="btn btn-link" href="{{ route('users.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.main')

@section('title', 'Edit a User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit User</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('users.update',[$user->id]) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {{ csrf_field() }}

                            @include('users/partials/fields')


                            <div id="app"> {{--The Vue application--}}
                                <bss-tree
                                     options-string="{{$userGroups}}"
                                     title="{{$title}}"
                                     initial-id = "{{$user->user_group_id}}">
                                </bss-tree>
                            </div> {{--app--}}


                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update User
                                    </button>

                                    <a class="btn btn-link" href="{{ route('users.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div> {{--panel body--}}
            </div> {{--panel--}}
            </div>
        </div> {{--row--}}
    </div> {{--container--}}

@endsection

resources/views/users/index.blade.php
@extends('layouts/main')

@section('title', 'List User Groups')


@section('include-css')
    <link  href="{{ asset('css/datatables.min.css') }}" rel="stylesheet" />
@endsection

@section('content')



<div class="container">

    <div class="row">
        <div class="col-xs-12">
            <h1>Users
            @can('create', \App\Models\User::class)
                <a href="{{ route('users.create') }}" class="btn btn-primary pull-right">Add User</a>
            @endcan
            </h1>
        </div>
    </div>


    <div class="row">
        <div class="col-xs-12">

            <table class="table table-striped table-bordered dataTable" id ="users">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Role</th>

                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($users as $user)
                            <tr>
                                <td>{{ $user->name }}</td>
                                <td>{{ $user->roleName() }}</td>
                                <td>
                                    <a href="{{ route('users.show', $user->id) }}" class="btn btn-default pull-left" style="margin-right:4px">View Details</a>

                                    @can('edit', \App\Models\User::class)
                                        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary pull-left" style="margin-right:4px">Edit</a>
                                        <a class="btn btn-danger" onclick="destroy({{$user->id}})">Delete</a>
                                    @endif


                                </td>
                            </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div> {{--row--}}



</div>

@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/users-common.js') }}"></script>
@endsection

@section('script')
<script>
    $(document).ready(function() {
        $('#users').DataTable();
    } );

</script>
@endsection

resources/views/users/show.blade.php
@extends('layouts.main')

@section('title', 'User')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">User</div>
                    <div class="panel-body">

                        {{--Name--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Name</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->name}}</span>
                            </div>
                        </div>

                        {{--Email--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Email</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->email}}</span>
                            </div>
                        </div>

                        {{--Role--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Role</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->roleName()}}</span>
                            </div>
                        </div>

                        {{--User Group--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>User Group</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$user->user_group->name}}</span>
                            </div>
                        </div>






                    </div>
                    <div class="panel-footer">
                        <a class="btn btn-primary mr1" href="{{ route('users.edit', [$user]) }}">Edit User</a>

                        <a class="btn btn-danger" onclick="destroy({{$user->id}})">Delete User</a>

                    </div>
                </div> {{--panel--}}



                <div>
                    <a class="btn btn-default" a href="{{ route('users.index') }}"><span class="icon-return"></span>Back to User list</a>
                </div>



            </div>
        </div> {{--container--}}
    </div>
@endsection

@section('script')

    <script src="{{ asset('js/users-common.js') }}"></script>

@endsection