routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', function() {
    return redirect()->route('home');
});


//mbtodo auth?
Route::get('/new-user-reset/{token}/{id}', 'UserController@newUserReset')->name('new-user-reset');
Route::post('/new-user-reset', 'UserController@savePassword')->name('new-user-save-password');




Route::get('/', 'DashboardController@index')->name('home');

Route::get('/message-page', 'DashboardController@messagePage')->name('message-page');


//Route::get('/login/with-aad/{context?}', 'Auth\External\AzureActiveDirectoryController@login')->name('login.aad');
Route::get('/login/with-aad', 'Auth\External\AzureActiveDirectoryController@loginStart')->name('login.aad.start');
Route::get('/login/with-aad/{application?}', 'Auth\External\AzureActiveDirectoryController@loginResponse')->name('login.aad.response');
Route::get('/logout/with-aad/{application?}', 'Auth\External\AzureActiveDirectoryController@logout');

//user groups

Route::group(['middleware'=>'auth'], function() {

    Route::get('user-groups/select', 'UserGroupController@selectList')->name('user-groups.select-list');
    Route::post('user-groups/select', 'UserGroupController@select')->name('user-groups.select');



    Route::get('user-groups/admin', 'UserGroupController@admin')->name('user-groups.admin');
    Route::get('user-groups/link', 'UserGroupController@initiateLink')->name('user-groups.link');
    Route::get('user-groups/select/none', 'UserGroupController@selectNone')->name('user-groups.select-none');


    Route::get('user-groups/deselect/{user_group}', 'UserGroupController@deselect')->name('user-groups.deselect');
    Route::get('user-groups/request-access/{user_group}', 'UserGroupController@requestAccess')->name('user-groups.requestaccess');
    Route::get('user-groups/autocomplete', 'UserGroupController@autocomplete')->name('user-groups.autocomplete');
    Route::resource('user-groups', 'UserGroupController');


    Route::resource('users','UserController');


});



//Created a new group, without the azure prefix
Route::group(['middleware'=>'auth', 'namespace'=>'CloudService'], function() {

    //Agreements
    Route::get('agreements/make', 'AgreementController@make')->name('agreements.make');
    Route::resource('agreements', 'AgreementController');
    Route::get('agreements/{agreement}/delete', 'AgreementController@delete')->name('agreements.delete');
    Route::get('agreements/{agreement}/discover', 'AgreementController@discover')->name('agreements.discover');
    Route::get('agreements/{agreement}/add-subscription', 'AgreementController@addSubscription')->name('agreements.add-subscription');

    //Margins
    Route::get('agreements/{agreement}/margins', 'AgreementController@showMargins')->name('agreements.margins.show');
    Route::get('agreements/{agreement}/margins/edit', 'AgreementController@editMargins')->name('agreements.margins.edit');
    Route::post('agreements/{agreement}/margins', 'AgreementController@storeMargins')->name('agreements.margins.store');


});


Route::group(['middleware'=>'auth', 'namespace'=>'CloudService', 'prefix'=>'/services/azure'], function() {
    Route::get('', 'AzureController@index')->name('azure.index');
    //Route::get('discover', 'AzureController@discover')->name('azure.discover');
    Route::get('subscriptions/{subscription}/usage', 'AzureSubscriptionController@usage')->name('azure.subscriptions.usage');

    Route::resource('subscriptions', 'AzureSubscriptionController', ['as'=>'azure']);
    Route::get('subscriptions/{subscription}/delete', 'AzureSubscriptionController@delete')->name('azure.subscriptions.delete');
    Route::get('subscriptions/{subscription}/connect', 'AzureSubscriptionController@connect')->name('azure.subscriptions.connect');
    Route::post('subscriptions/{subscription}/attach', 'AzureSubscriptionController@attach')->name('azure.subscriptions.attach');
    Route::get('subscriptions/{subscription}/check', 'AzureSubscriptionController@check')->name('azure.subscriptions.check');
});

Route::group(['middleware'=>'auth', 'namespace'=>'CloudService', 'prefix'=>'/services/aad'], function() {
    Route::get('tenants/{aadTenant}/connect/{applicationName?}', 'MicrosoftAadTenantController@connect')->name('aad.tenants.connect');
    Route::post('tenants/{aadTenant}/attach/{applicationName?}', 'MicrosoftAadTenantController@attach')->name('aad.tenants.attach');
});



// TESTS! ---------------------------------------------------------------------------------------------------------------
Route::get('/azure-test', 'CloudService\AzureController@test')->name('azure.test');
Route::get('/tests', 'TestController@index');
Route::get('/tests/ea', 'TestController@eaApi');
Route::get('/tests/partner', 'TestController@partnerApi');
Route::get('/tests/reports', 'TestController@reports');
Route::get('/tests/add-azure-agreement/{which}', 'TestController@addAzureAgreement');

Route::group(['middleware'=>'auth', 'prefix'=>'/data'], function() {
    Route::get('/azure/agreements/count', 'DataController@azureAgreementCount');
    Route::get('/azure/subscriptions/count', 'DataController@azureSubscriptionCount');
    //Route::get('/azure/spend/{month?}', 'DataController@azureSpend');
    //Route::get('/azure/spend2', 'DataController@azureSpend2');
    Route::get('/azure/spend', 'DataController@azureSpend');
});

app/Http/Controllers/UserGroupController.php
<?php

namespace App\Http\Controllers;

//Models
use App\Http\Requests\StoreUserGroup;
use App\Models\Customer;
use App\Models\Microsoft\AadTenant;

use App\Models\UserGroup;

//Laravel


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;


class UserGroupController extends Controller
{


    public function __construct()
    {
        //User group must be selected for all these functions
        $this->middleware('userGroupSelected')->except(['select','selectList','test']);
    }


    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //don't auth, only display a list of this users groups
        $user = auth()->user();

        //once we have a selected user_group, only show descendants
        $userGroups = UserGroup::getSelectedAndDescendants();

        $canEdit = $user->isAdmin();

        return view('user-groups.index',compact('userGroups','canEdit'));
    }


    /**
     * Show the form to create new.
     * Spin up an empty UserGroup for the fields.
     *
     * @param UserGroup $userGroup
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create(UserGroup $userGroup)
    {
        $this->authorize('create', UserGroup::class);

        //only allow types below
        $userGroupTypes = collect(UserGroup::getRolesBelowCurrent());

        return view('user-groups.create',compact('userGroupTypes','userGroup'));
    }


    /**
     * Validate and save to the db.
     *
     * @param StoreUserGroup $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(StoreUserGroup $request)
    {
        //auth in form request

        $userGroup = new UserGroup();
        $userGroup->name = $request->input('name');
        $userGroup->type = $request->input('type');

        $userGroup->properties = $request->input('properties');

        $userGroup->save();

        //just make the selected group the parent
        $selectedGroup = session('selectedUserGroup');

        $selectedGroup->appendNode($userGroup);

        return redirect()->route('user-groups.show', ['userGroup' => $userGroup->id]);
    }


    /**
     * Just show the user group
     * @param UserGroup $userGroup
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function show(UserGroup $userGroup)
    {
        $this->authorize('show', $userGroup);

        //get the description for this id
        $userGroupType = UserGroup::findTypeNameWithID($userGroup->type);

        $users = $userGroup->users;

        return view('user-groups.show',compact('userGroup','userGroupType','users'));
    }

    /**
     * Show the form for editing the specified resource.
     * @param UserGroup $userGroup
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(UserGroup $userGroup)
    {
        $this->authorize('update', $userGroup);

        //get the description for this id
        $userGroupType = UserGroup::findTypeNameWithID($userGroup->type);

        $userGroupTypes = collect(UserGroup::TYPES);

        return view('user-groups.edit',compact('userGroup','userGroupType','userGroupTypes'));
    }

    /**
     * Save the changes.
     *
     * @param Request $request
     * @param UserGroup $userGroup
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request,UserGroup $userGroup)
    {
        //auth in form request

        $userGroup->name = $request->input('name');
        $userGroup->type = $request->input('type');
        $userGroup->properties = $request->input('properties');

        $userGroup->save();

        showMessage('success','User group updated.');

        return redirect()->route('user-groups.show', ['userGroup' => $userGroup->id]);
    }

    /**
     * Remove the specified resource from storage.
     * AJAX
     * @param UserGroup $userGroup
     * @return void
     * @throws \Exception
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(UserGroup $userGroup)
    {
        $this->authorize('destroy', $userGroup);

        $userGroup->safeDelete();
    }



    /**
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function selectNone(Request $request)
    {
        $request->session()->remove('selectedUserGroup');

        return redirect(route('home'));
    }

    /**
     * @param Request $request
     * @param Customer $customer
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function deselect(Request $request, Customer $customer)
    {
        // unset this customer in session for future usage, if allowed:
        $this->authorize('view', $customer);

        $selected = $request->session()->get('selectedUserGroup');

        if (array_key_exists(strval($customer->id), $selected)) {
            unset($selected[strval($customer->id)]);
        }
        if (count($selected) == 0) {
            $request->session()->forget('selectedUserGroup');
        } else {
            $request->session()->put('selectedUserGroup', $selected);
        }
        return redirect(route('home'));
    }


    /**
     * User has selected a user group
     * add it in the session
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function select(Request $request)
    {
        $userGroup = UserGroup::findOrFail($request->user_group_id);

        $this->authorize('select', $userGroup);

        // select this specific customer only
        $request->session()->put('selectedUserGroup', $userGroup);

        return $this->redirectIfHaveIntendedRoute($request);

    }


    /**
     * Is the session has a saved route, then return to it
     * @param $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    private function redirectIfHaveIntendedRoute($request)
    {
        if ($request->session()->has('intended_route')) {
            $redirectTo = $request->session()->pull('intended_route');
            if (strpos($redirectTo, 'https://') === 0) {
                return redirect($redirectTo);
            }
            return redirect()->route($redirectTo);
        }else{
            return redirect(route('home'));
        }

    }


    /**
     * Present the Select a Customer page
     * Should show all thus user's user_group descendants.
     * @param Request $request
     * @return mixed
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function selectList(Request $request)
    {

        $this->authorize('selectList', UserGroup::class);

        $user = Auth::user();

        $userGroups = UserGroup::getTreeForSelectedUser();

        $userID = $user->id;
        $title = "User Group";

        return view('user-groups.select', compact('userGroups','userID','title','user'));
    }


    /**
     * Show the admin page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function admin()
    {

        $this->authorize('administer', UserGroup::class);

        //is this customer linked to aad?
        $aadTenant = AadTenant::where('user_group_id', '=', auth()->user()->user_group_id)->first();
        $aadLinked = ($aadTenant ? true : false);
        return view('user-groups.admin')->with(compact(['aadLinked']));


    }

}

resources/views/user-groups/admin.blade.php
@extends('layouts/main')

@section('title', 'User Group Administration')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-xs-12">

                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h1 class="panel-title">User Group Administration</h1>
                    </div>
                    <div class="panel-body">

                        @if($aadLinked)
                            <a href="{{ route('login.aad.start')}}" class="btn btn-primary disabled">Allow Microsoft Login</a>
                        @else
                            <a href="{{ route('login.aad.start')}}" class="btn btn-primary">Allow Microsoft Login</a>
                        @endif

                    </div>

                    <div class="panel-footer">

                    </div>

                </div>



            </div>
        </div>

    </div>

@endsection

resources/views/user-groups/create.blade.php
@extends('layouts/main')

@section('title', 'Add a User Group')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Add a User Group</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('user-groups.store') }}">
                            {{ csrf_field() }}


                            @include('user-groups/partials/fields')

                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Add User Group
                                    </button>

                                    <a class="btn btn-link" href="{{ route('user-groups.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

resources/views/user-groups/edit.blade.php
@extends('layouts/main')

@section('title', 'Edit User Group')

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">Edit User Group</div>
                    <div class="panel-body">
                        @include('partials/forms/errors')
                        <form class="form-horizontal" role="form" method="POST" action="{{ route('user-groups.update',[$userGroup->id]) }}">
                            <input type="hidden" name="_method" value="PUT">
                            {{ csrf_field() }}


                            @include('user-groups/partials/fields')
                          
                            <div class="form-group">
                                <div class="col-md-8 col-md-offset-4">
                                    <button type="submit" class="btn btn-primary">
                                        Update User Group
                                    </button>

                                    <a class="btn btn-link" href="{{ route('user-groups.index') }}">
                                        Cancel
                                    </a>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>

            </div>

        </div>
    </div>

@endsection

resources/views/user-groups/index.blade.php
@extends('layouts/main')

@section('title', 'List User Groups')


@section('include-css')
    <link  href="{{ asset('css/datatables.min.css') }}" rel="stylesheet" />
@endsection

@section('content')



<div class="container">

    <div class="row">
        <div class="col-xs-12">
            <h1>User Groups
            @can('create', \App\Models\UserGroup::class)
                <a href="{{ route('user-groups.create') }}" class="btn btn-primary pull-right">Add User Group</a>
            @endcan
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-12">

            <table class="table table-bordered table-striped" id ="user-groups">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Type</th>
                        <th>Parent</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($userGroups as $userGroup)
                            <tr>
                                <td>{{ $userGroup->code }}</td>
                                <td>{{ $userGroup->name }}</td>
                                <td>{{ $userGroup->getTypeName() }}</td>
                                <td>{{ $userGroup->getParentName() }}</td>
                                <td>
                                @if($userGroup->name != \App\Models\UserGroup::MASTER_NAME && $userGroup->name != 'Bytes' )
                                    <a href="{{ route('user-groups.show', $userGroup->id) }}" class="btn btn-default pull-left" style="margin-right:4px">View Details</a>
                                    @if($canEdit)
                                            <a href="{{ route('user-groups.edit', $userGroup->id) }}" class="btn btn-info pull-left" style="margin-right:4px">Edit</a>
                                            <a class="btn btn-danger" onclick="destroy({{$userGroup->id}})">Delete</a>
                                    @endif
                                    </td>
                                @endif
                            </tr>
                    @endforeach
                </tbody>
            </table>

        </div>
    </div> {{--row--}}



</div>

@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/user-groups-common.js') }}"></script>
@endsection

@section('script')
<script>
    $(document).ready(function() {
        $('#user-groups').DataTable();
    } );

</script>
@endsection

resources/views/user-groups/select.blade.php
@extends('layouts/main')

@section('title', 'Select User Group')

@section('include-css')
    <link href="{{ asset('css/datatables.min.css') }}" rel="stylesheet"/>
@endsection

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-xs-8">
                <h1>Select a User Group</h1>
            </div>
        </div>

        <div class="row">
            <div class="col-xs-10">

                <form class="form-horizontal" role="form" method="POST" action="{{ route('user-groups.select') }}">
                    {{ csrf_field() }}
                    <div id="app"> {{--The Vue application--}}
                        <bss-tree
                                options-string="{{$userGroups}}"
                                title="{{$title}}"
                                initial-id="{{$user->user_group_id}}">
                        </bss-tree>
                    </div> {{--app--}}

                    <div class="row">
                        <div class="col-xs-10">
                            <button type="submit" class="btn btn-primary pull-right">
                                Select User Group
                            </button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>




@endsection

@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
@endsection

@section('script')
    <script>
        $(document).ready(function () {
            $('#user-groups').DataTable();
        });

    </script>
@endsection

resources/views/user-groups/show.blade.php
@extends('layouts/main')

@section('title', 'User Group')

@section('include-css')
    <link  href="{{ asset('css/datatables.min.css') }}" rel="stylesheet" />
@endsection

@section('content')

    <div class="container">

        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-heading">User Group</div>
                    <div class="panel-body">

                        {{--Name--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Name</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$userGroup->name}}</span>
                            </div>
                        </div>

                        {{--Type--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Type</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$userGroupType}}</span>
                            </div>
                        </div>

                        {{--Code--}}
                        <div class="row mt1">
                            <div class="col-md-4 text-right">
                                <strong>Customer ID/Reference</strong>
                            </div>
                            <div class="col-md-6">
                                <span>{{$userGroup->code}}</span>
                            </div>
                        </div>




                    </div>
                    <div class="panel-footer">

                        @can('update',$userGroup)
                            <a class="btn btn-primary mr1" href="{{ route('user-groups.edit', [$userGroup]) }}">Edit User Group</a>
                        @endcan

                        @can('destroy',$userGroup)
                            <a class="btn btn-danger" onclick="destroy({{$userGroup->id}})">Delete User Group</a>
                        @endcan


                    </div>
                </div> {{--panel--}}


                @include('user-groups/partials/user-list')

                <div>
                    <a class="btn btn-default" a href="{{ route('user-groups.index') }}"><span class="icon-return"></span>Back to User Groups list</a>
                </div>


            </div>
        </div> {{--container--}}
    </div>
@endsection


@section('scripts')
    <script src="{{ asset('js/datatables.min.js') }}"></script>
    <script src="{{ asset('js/user-groups-common.js') }}"></script>
@endsection


@section('script')
    <script>
        $(document).ready(function() {
            $('#users').DataTable();
        } );

    </script>
@endsection